### ISSUE TITLE
Would it ever be possible to use fwupd on macOS to do these updates?

### ISSUE THREAD

**Issue by memon** [flhofer/dell_TB16_firmware#3]
i'm able to install fwupd via homebrew on my m1 macbook and the dock does show up in system information in mac but fwupd doesn't see it. do you think it'll ever be possible to update the dell tb16 using macOS?

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/d5ee2be7-8e55-43de-82c5-17e4abc52c55">
<img width="772" alt="image" src="https://github.com/user-attachments/assets/37d80e05-d391-4012-a0be-19c5b4a862bc">

PS. thanks for all your work on this, amazing effort.

**Comment by flhofer** [comment]
Hi @memon 

Welcome. Unfortunately it is hard to tell. I have a vague memory that sudo on macs is not the same as on Linux distros, i.e. you don't really have all privileges.

As for flashing, it should work to just boot a 24.04 lts live and flash it from there. Give it a go, it's just a one-time thing anyway
