### ISSUE TITLE
Where to download firmware binaries

### ISSUE THREAD

**Issue by peacechen** [flhofer/dell_TB16_firmware#4]
I can't find the cab/bin files online. I downloaded the Dell TB16 updater exe for Windows, but am having a heck of a time extracting it. I even ran it on a Windows box but don't see where it extracts the files to.

These are the only 2 Dell devices that show up from `fwupdmgr -get-devices`. Both are at fw 16.00 which matches the versions for the cable and dock. Should the MST1/2 devices also show?

```
├─Thunderbolt Cable:
│     Device ID:          010334a5a9f76b04af3830d78e9a515a96ceb7f0
│     Current version:    16.00
│     Vendor:             Dell (THUNDERBOLT:0x00D4, TBT:0x00D4)
│     GUIDs:              6634407c-6706-5fe9-907e-37efcbc8098a ← THUNDERBOLT\VEN_00D4&DEV_B051
│                         b4fd3cdf-4e3a-5090-a583-45367cfd6421 ← TBT-00d4b051
│                         8564922d-2c7a-5169-9cff-d3e73f0bd807 ← TBT-00d4b051-controller0-1
│     Device Flags:       • Updatable
│                         • System requires external power source
│                         • Device stages updates
│                         • Signed Payload
│   
├─Thunderbolt Dock:
│     Device ID:          b0cfe5568cd559d5e3a2fdd1b8b4b00f8a41d089
│     Current version:    16.00
│     Vendor:             Dell (THUNDERBOLT:0x00D4, TBT:0x00D4)
│     GUIDs:              1fa96dfa-7407-50b2-87d4-4ae4351c3867 ← THUNDERBOLT\VEN_00D4&DEV_B054
│                         76cc74d4-f062-5b93-a11c-8d2a58a25848 ← TBT-00d4b054
│                         f5a71973-58f2-5638-9c9a-d9c7538d6772 ← TBT-00d4b054-controller0-301
│     Device Flags:       • Updatable
│                         • System requires external power source
│                         • Device stages updates
│                         • Signed Payload
```

**Comment by flhofer** [comment]
Hi!


All the firmwares are available in this repository. Choose the newest unless you're using a mac

Also, you want see the mst devices unless you connect a monitor to at least one of each mst's outputs. It is also possible that they won't show unless you update the nvm firmware first. (Issue with cable fw)

Try it out and let me know

**Comment by peacechen** [comment]
I totally missed the firmware files in bin. Thanks for providing those! I was able to successfully update the dock, cable, HDMI and DP firmwares to the latest versions using your instructions. The DP output works great at 4k 60Hz, whereas it never worked before the upgrade. You're a lifesaver!

**Comment by flhofer** [comment]
welcome :)
